"""create call_logs table

Revision ID: 02244f6c30d9
Revises: 341e3b52577a
Create Date: 2024-12-11 12:13:48.085935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02244f6c30d9'
down_revision: Union[str, None] = '341e3b52577a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_logs',
    sa.Column('call_log_id', sa.UUID(), nullable=False),
    sa.Column('caller_phonenumber', sa.UUID(), nullable=False),
    sa.Column('receiver_phonenumber', sa.UUID(), nullable=False),
    sa.Column('call_start_time', sa.DateTime(), nullable=False),
    sa.Column('call_end_time', sa.DateTime(), nullable=True),
    sa.Column('call_duration', sa.Float(), nullable=True),
    sa.Column('call_type', sa.Enum('INCOMING', 'OUTGOING', 'MISSED', 'REJECTED', name='calltype'), nullable=False),
    sa.Column('call_status', sa.Enum('COMPLETED', 'FAILED', 'NO_ANSWER', 'BUSY', name='callstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['caller_phonenumber'], ['phonenumbers.phonenumber_id'], ),
    sa.ForeignKeyConstraint(['receiver_phonenumber'], ['phonenumbers.phonenumber_id'], ),
    sa.PrimaryKeyConstraint('call_log_id')
    )
    op.create_index(op.f('ix_call_logs_call_log_id'), 'call_logs', ['call_log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_logs_call_log_id'), table_name='call_logs')
    op.drop_table('call_logs')
    # ### end Alembic commands ###
