"""create phonenumbers table

Revision ID: 341e3b52577a
Revises: d280fea76338
Create Date: 2024-12-11 12:11:23.385024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '341e3b52577a'
down_revision: Union[str, None] = 'd280fea76338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phonenumbers',
    sa.Column('phonenumber_id', sa.UUID(), nullable=False),
    sa.Column('phonenumber', sa.String(length=15), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('phonenumber_id')
    )
    op.create_index(op.f('ix_phonenumbers_phonenumber'), 'phonenumbers', ['phonenumber'], unique=True)
    op.create_index(op.f('ix_phonenumbers_phonenumber_id'), 'phonenumbers', ['phonenumber_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phonenumbers_phonenumber_id'), table_name='phonenumbers')
    op.drop_index(op.f('ix_phonenumbers_phonenumber'), table_name='phonenumbers')
    op.drop_table('phonenumbers')
    # ### end Alembic commands ###
