"""rename phonenumber to number in phonenumbers table

Revision ID: 38549021d275
Revises: 02244f6c30d9
Create Date: 2024-12-11 14:41:04.590234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38549021d275'
down_revision: Union[str, None] = '02244f6c30d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phonenumbers', sa.Column('number', sa.String(length=15), nullable=True))
    op.drop_index('ix_phonenumbers_phonenumber', table_name='phonenumbers')
    op.create_index(op.f('ix_phonenumbers_number'), 'phonenumbers', ['number'], unique=True)
    op.drop_column('phonenumbers', 'phonenumber')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phonenumbers', sa.Column('phonenumber', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_phonenumbers_number'), table_name='phonenumbers')
    op.create_index('ix_phonenumbers_phonenumber', 'phonenumbers', ['phonenumber'], unique=True)
    op.drop_column('phonenumbers', 'number')
    # ### end Alembic commands ###
