name: Python Test Workflow

on:
  push:
    branches:
      - side
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Check out the repository code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set PYTHONPATH env variable
        run: | 
          echo $(pwd)
          ls

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      # - name: Run tests
      #   run: |
      #     pytest  # Replace with your test runner or command

      # - name: Upload test results (optional)
      #   if: always()  # Always execute this even if tests fail
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: test-results
      #     path: ./test-results/  # Update this path if you're saving test results
