name: Python Test Workflow

on:
  push:
    branches:
      - side
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: | 
            docker buildx build --platform linux/amd64 --tag myapp-image:latest .

      - name: Run Container
        run: |
            docker run --rm myapp-image:latest /bin/bash -c "pytest"


      # - name: Run Tests
      #   run: |
      #     docker run -it --rm my-image:latest pytest
        

